version: '3.9'

services:
  backend:
    build: .
    container_name: datawise-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/datawise
    volumes:
      - .:/app

  mongo:
    image: mongo:6
    container_name: datawise-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
